- src/App.jsx
- src/components/header/Header.jsx
- src/components/header/Header.style.js
> #2 
* 좌우 여백동일하게 변경, PC버전 글꼴 키움
* toggleMenu가 활성화 되었을 때 Wiscom을 눌러도 home으로 이동하지 않는 문제 해결
* toggleMenu에서 다른 항목 클릭 후 NavItem이 사라지는 동안 바로 페이지로 이동하지 않도록 딜레이 추가
> 💄 Design: 헤더 UI 수정

- src/App.jsx
- src/components/header/Header.jsx
- src/components/header/Header.style.js
- src/index.css
> 🩹 Fix: Header 메뉴 아이템 애니메이션 수정

- src/components/workdetail/WorkDetail.style.js
> #7 
* 모바일 버전 margin-bottom 추가
> 💄 Design: 모바일 버전 margin-bottom 추가

- src/assets/img/detail_cd_case.svg
> 💄 Design: CD 케이스 이미지 크기 키움

- src/components/header/Header.style.js
> 💄 Design: Nav Item 폰트 크기 키움

- src/components/header/Header.style.js
> 💄 Design: Nav Item 왼쪽 margin 조정

- package.json
- src/components/workdetail/button/LeftButton.jsx
- src/components/workdetail/button/RightButton.jsx
- src/components/workdetail/button/ViewSite.style.js
- src/components/workdetail/cdcase/CdCase.jsx
- src/components/workdetail/leftcomponent/LeftContent.jsx
- src/components/workdetail/mobile/WorkIntroduce.jsx
- src/components/workdetail/worktitle/WorkTitle.style.js
- src/pages/WorkDetail.jsx
- yarn.lock
#7 
* API 통신
* 아직 리스트 > 상세 조회 구현이 안되어서 임시로 https://2024wiscom-backend.store/api/works/category/big_data/2 해당 경로로 요청
* prev, next 버튼 동작
* 테블릿, 모바일 버전의 이미지 <> 버튼 동작
> ✨ Feat: 작품 상세 조회 API 통신

- src/components/workdetail/mobile/WorkIntroduce.jsx
- src/pages/WorkDetail.jsx
#7 
api 초기값 지정, 테블릿 모바일 버전 페이지 변경 시 이미지 index 초기화
> 🐛 Fix: api 초기값 지정, 테블릿 모바일 버전 페이지 변경 시 이미지 index 초기화

- src/components/header/Header.style.js
> 💄 Design: NavItem 폰트 크기 줄임, 간격 조정

- vercel.json
#30
- /work-detail로 접근 시 404 not found 에러 뜨는 거 수정
> 🐛 Fix: 404페이지 에러 수정

- src/components/workdetail/WorkDetail.style.js
- src/components/workdetail/button/Button.style.js
- src/components/workdetail/button/ImageLeftButton.jsx
- src/components/workdetail/button/ImageRightButton.jsx
- src/components/workdetail/developer/Developer.style.js
- src/components/workdetail/mobile/WorkIntroduce.jsx
- src/components/workdetail/mobile/WorkIntroduce.style.js
- src/components/workdetail/rightcomponent/RightContent.jsx
> 💄 Design: work detail 페이지 css 조정

- src/components/header/Header.style.js
#2 
- 실제 모바일 환경에서 보면 z 플립이 잘려서 폰트 크기 줄임 
> 💄 Design: 모바일 header 메뉴 폰트 크기 줄임

- src/components/workdetail/button/ViewSite.style.js
- src/components/workdetail/developer/Developer.style.js
- src/components/workdetail/image/Image.style.js
- src/components/workdetail/rightcomponent/RightContent.style.js
- src/components/workdetail/worktitle/WorkTitle.style.js
- src/pages/WorkDetail.jsx
> 💄 Design: work detail 반응형 문제 진행 중

- src/components/workdetail/image/Image.style.js
> 💄 Design: min-width: 0px로 변경

- src/components/worklist/Slide.style.js
> 💄 Design: 작품 목록 슬라이드 마진값 추가

- src/components/home/Home.style.js
> #3 
- 홈 화면 반응형 수정 및 추가 (태블릿 세로 버전)
- 가로, 세로 스크롤 방지
- 하단 마진 추가
> 💄 Design: 홈 화면 반응형 추가

- src/components/guestBook/MessageInputSection.jsx
Guest Book message 글자수 제한 삭제
> close #번호
> :fire: Guest Book message 글자수 제한 삭제

- src/components/guestBook/GuestBook.style.js
- src/components/guestBook/MessageCard.style.js
- src/components/guestBook/MessageGrid.jsx
- src/components/guestBook/MessageGrid.style.js
- src/components/guestBook/MessageInputSection.jsx
- src/components/guestBook/MessageInputSection.style.js
- src/components/guestBook/Pagination.style.js
- src/components/guestBook/SearchBar.jsx
- src/components/guestBook/SearchBar.style.js
- src/components/guestBook/button/SendMessageButton.js
- src/components/guestBook/button/ViewGuestBookButton.js
- src/pages/GuestBook.jsx
> Feature/guestbook 모바일 UI 추가 

- src/components/guestBook/Pagination.jsx
> :memo: Vector 경로 수정

- src/components/worklist/Slide.jsx
- vercel 2.json
> #4
- 태블릿, 데스크톱 화면에서 데이터 개수 적을 때 표시 안 되는 오류 해결
> 🐛 태블릿, 데스크톱 화면에서 데이터 개수 적을 때 표시 안 되는 오류 해결

- src/components/header/Header.style.js
> 💄 Design: 햄버거 바 간격, 위치 수정 

- src/pages/WorkDetail.jsx
> ♻️ Refactor: PC 버전에서 스크롤 위로 이동하지 않음

- src/components/workdetail/button/ViewSite.style.js
> 💄 Design: Visit Site 배치 정렬

- src/components/guestBook/GuestBook.style.js
- src/components/guestBook/MessageCard.style.js
- src/components/guestBook/MessageGrid.style.js
- src/components/guestBook/MessageInputSection.style.js
- src/components/guestBook/SearchBar.style.js
Guest Book 반응형 CSS update
> close #번호
> :lipstick: Guest Book 반응형 CSS update

- src/components/guestBook/MessageCard.style.js
- src/components/guestBook/MessageInputSection.style.js
- src/components/guestBook/SearchBar.style.js
Guest Book label-from CSS update
> close #번호
> :lipstick: Guest Book label-from CSS update

- src/components/footer/Footer.jsx
Footer instagram url add
> close #번호
> :sparkles: Footer instagram url add

- src/components/guestBook/MessageCard.style.js
- src/components/guestBook/MessageInputSection.style.js
- src/components/guestBook/Pagination.jsx
Guest Book pagination update
> close #번호
> :lipstick: Guest Book pagination update

- src/components/about/About.style.js
> 💄 Design: About 모바일 이미지 및 폰트 크기 수정

- src/components/about/About.style.js
> 💄 Design: About 모바일 반응형 수정

- src/components/about/About.style.js
> ✅ Test: Github Action 테스트

- src/components/about/About.style.js
> 💄 Design: Map 팀 정렬 gap 수정

- index.html
> 🚀 Deploy: 프로젝트 title 수정

- src/components/workdetail/developer/Developer.style.js
> 💄 Design: DeveloperPosition 텍스트가 길 경우 css 깨짐 해결

- src/components/workdetail/mobile/WorkIntroduce.jsx
- src/components/workdetail/rightcomponent/RightContent.jsx
> ♻️ Refactor: url 이 null일 경우 아이콘 출력하지 않음

- src/components/footer/Footer.style.js
- src/components/guestBook/Pagination.style.js
Footer padding update
> close #번호
> :lipstick: Footer padding update

- src/components/guestBook/MessageCard.style.js
- src/components/guestBook/MessageInputSection.style.js
> Feature/guestbook from 중첩 - font size 줄이기 

- src/components/guestBook/MessageInputSection.jsx
- src/components/guestBook/MessageInputSection.style.js
Guest Book from label length 조절
> close #번호
> :lipstick: Guest Book from label length 조절(글씨쓰기 시작하면 왼쪽으로 이동)

- src/components/worklist/WorkItem.jsx
- src/components/worklist/WorkItem.style.js
> 🐛 Fix: 타이틀 overflow일 때 애니메이션 적용

- src/App.jsx
- src/components/workdetail/mobile/WorkIntroduce.jsx
- src/components/worklist/WorkItem.jsx
- src/pages/WorkDetail.jsx
> 🐛 Fix: id 값 파라미터 포함

- src/components/workdetail/developer/Developer.style.js
- src/components/workdetail/rightcomponent/RightContent.style.js
> 🐛 Fix: 텍스트 겹치는 문제 해결

- src/components/guestBook/MessageInputSection.style.js
- src/pages/GuestBook.jsx
Guest Book UI update
> close #번호
> :lipstick: Guest Book UI update

- src/components/footer/Footer.style.js
> :lipstick: Footer UI update

- src/components/guestBook/MessageInputSection.style.js
guestBook UI update
> close #번호
> :lipstick: GuestBook UI update

- src/components/guestBook/MessageInputSection.style.js
GuestBook Button margin update
> close #번호
> :lipstick: GuestBook Button margin update

- src/components/guestBook/MessageInputSection.style.js
guestbook height update
> close #번호
> :lipstick: Guestbook height update

- src/components/guestBook/MessageInputSection.style.js
- src/components/guestBook/SearchBar.style.js
guestBook searchbar UI update
> close #번호
> :lipstick: GuestBook searchbar UI update

- src/components/workdetail/leftcomponent/LeftContent.jsx
- src/components/workdetail/rightcomponent/RightContent.jsx
> 🐛 Fix: 데이터 변경되면 슬라이드 위로 올림

- src/components/guestBook/MessageCard.style.js
- src/components/guestBook/MessageInputSection.style.js
GuestBook UI 여백,from update
> close #번호
> :lipstick: GuestBook UI 여백,from update

- src/pages/WorkDetail.jsx
> 🔥 Remove: 불필요한 주석 삭제

- src/components/footer/Footer.style.js
footer logo px로 수정
> close #번호
> :lipstick: Footer logo px로 수정

- src/components/guestBook/MessageInputSection.style.js
guest Book to 겹치는 부분 수정
> close #번호
> :lipstick: Guest Book to 겹치는 부분 수정

- src/components/about/Introduction.jsx
- src/components/about/NewCongratulation.jsx
> 🐛 Fix: About 이미지 경로 수정

- src/components/footer/Footer.style.js
> :lipstick: Footer 줄바꿈 방지

- src/components/guestBook/MessageInputSection.style.js
guest Book desktop ver UI height  줄이기
> close #번호
> :lipstick: Guest Book desktop ver UI height  줄이기

- src/components/about/About.style.js
- src/components/about/Introduction.jsx
- src/components/about/NewCongratulation.jsx
> 🐛 Fix: About 이미지 화질 개선

- src/components/about/About.style.js
#1
- About 이미지 배포판에서 위치 이상 이슈 수정
> 🐛 Fix: About 이미지 배포판에서 위치 문제 수정

- src/components/about/About.style.js
> 🐛 Fix: About 이미지 배포판 높이 문제 수정

- src/components/about/About.style.js
> 🐛 Fix: About 이미지 배포판 높이 수정

- src/components/home/Home.jsx
- src/components/home/Home.style.js
> 🐛 Fix: Cd 이미지 화질 개선

- src/components/guestBook/MessageCard.style.js
- src/components/guestBook/MessageInputSection.jsx
- src/components/guestBook/MessageInputSection.style.js
- src/components/guestBook/SearchBar.style.js
guest Book 요청사항 update
> close #번호
> :lipstick: Guest Book 요청사항 update

- src/components/guestBook/MessageInputSection.style.js
guest Book textSection mobile font-size update
> close #번호
> :lipstick: Guest Book textSection mobile font-size update

- src/components/guestBook/MessageInputSection.style.js
guestbook textSection fontsize update
> close #번호
> :lipstick: Guestbook textSection fontsize update

- src/components/guestBook/MessageInputSection.jsx
> :bug: MaxLength 함수 추가
